import { createClient } from '@/utils/supabase/server'
import { NextResponse } from 'next/server'

export async function POST(req: Request) {
    try {
        const { name, email, education, experience, skills, projects } = await req.json()

        const supabase = createClient()
        const { data: { user }, error: authError } = await supabase.auth.getUser()

        if (authError || !user) {
            console.error("Backend Auth Error:", authError?.message || "User is null");
            return NextResponse.json({ error: 'Unauthorized: Please log in to generate resumes.' }, { status: 401 })
        }

        if (!process.env.OPENROUTER_API_KEY) {
            return NextResponse.json({ error: 'OpenRouter API key not configured' }, { status: 500 })
        }

        const systemPrompt = `You are an expert resume writer. Generate a highly professional, well-structured resume using the following user details.
        
Output ONLY in Markdown format, following EXACTLY this structure for maximum ATS and visual appeal:

# Contact
- **Name**: [Name]
- **Email**: [Email]
- **Phone**: [Phone]
- **Location**: [Location if provided]

# Summary
[A strong 2-3 sentence professional summary highlighting key expertise and years of experience, bolding key terms.]

# Experience
## [JOB TITLE], [COMPANY] ([DURATION])
---
- **[Action Verb]** [rest of the bullet point, focusing on impact and metrics].
- **[Action Verb]** [rest of the bullet point].

# Projects
## [PROJECT NAME] - [YOUR ROLE] ([DURATION])
---
- **[Action Verb]** [project description and impact].

# Education
## [DEGREE], [SCHOOL/UNIVERSITY] ([YEAR])
---
- **[Action Verb or Keyword]** [Any additional info or just keep it simple].

# Skills
- **[Category e.g., Programming languages]**: [Comma separated list]
- **[Category e.g., Frameworks]**: [Comma separated list]

Ensure all main section headers (#) are exactly as above. Ensure all subheaders (##) for experience, projects, and education are ALL CAPS and followed by a horizontal rule (---).`;

        const userPrompt = `
        User Details:
        - Name: ${name}
        - Email: ${email}
        - Education: ${JSON.stringify(education)}
        - Experience: ${JSON.stringify(experience)}
        - Projects: ${JSON.stringify(projects)}
        - Skills: ${skills}
        `

        console.log("Calling OpenRouter with model: openai/gpt-4o-mini");

        const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${process.env.OPENROUTER_API_KEY}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                model: "openai/gpt-4o-mini",
                messages: [
                    { role: "system", content: systemPrompt },
                    { role: "user", content: userPrompt },
                ],
            }),
        });

        const data = await response.json();
        console.log("OpenRouter Response:", JSON.stringify(data, null, 2));

        if (!response.ok) {
            return NextResponse.json({ error: data.error?.message || 'Failed to call OpenRouter' }, { status: response.status });
        }

        const content = data.choices?.[0]?.message?.content;

        if (!content) {
            return NextResponse.json({ error: 'No content generated by AI' }, { status: 500 });
        }

        // Store in Supabase
        console.log("Backend Auth resolved User ID:", user?.id);

        const { data: dbData, error: dbError } = await supabase
            .from('resumes')
            .insert([
                {
                    personal_info: { name, email, projects },
                    education: education || [],
                    experience: experience || [],
                    skills: typeof skills === 'string' ? skills.split(',').map((s: string) => s.trim()) : skills || [],
                    generated_content: content,
                    user_id: user?.id,
                },
            ])
            .select()

        if (dbError) {
            console.error('Supabase DB Insert Error:', dbError);
            return NextResponse.json({ error: 'Database storage failed: ' + dbError.message, content }, { status: 500 });
        }

        return NextResponse.json({ content, id: dbData?.[0]?.id });

    } catch (error: any) {
        console.error('API Error:', error)
        return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 })
    }
}
