'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Loader2, Plus, Trash2, CheckCircle } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { ExportPdfButton } from '@/components/ExportPdfButton'

export default function CreateResume() {
    const router = useRouter()
    const [isGenerating, setIsGenerating] = useState(false)
    const [step, setStep] = useState(1)
    const [generatedResume, setGeneratedResume] = useState<string | null>(null)

    // Form State
    const [personalInfo, setPersonalInfo] = useState({ name: '', email: '', phone: '', linkedin: '' })
    const [education, setEducation] = useState([{ degree: '', school: '', year: '' }])
    const [experience, setExperience] = useState([{ role: '', company: '', duration: '', description: '' }])
    const [projects, setProjects] = useState([{ name: '', role: '', duration: '', description: '' }])
    const [skills, setSkills] = useState('')

    const handleAddEducation = () => setEducation([...education, { degree: '', school: '', year: '' }])
    const handleRemoveEducation = (index: number) => setEducation(education.filter((_, i) => i !== index))

    const handleAddExperience = () => setExperience([...experience, { role: '', company: '', duration: '', description: '' }])
    const handleRemoveExperience = (index: number) => setExperience(experience.filter((_, i) => i !== index))

    const handleAddProject = () => setProjects([...projects, { name: '', role: '', duration: '', description: '' }])
    const handleRemoveProject = (index: number) => setProjects(projects.filter((_, i) => i !== index))

    const handleGenerate = async () => {
        setIsGenerating(true)
        try {
            console.log("Starting generation with skills:", skills);

            const response = await fetch('/api/generate-resume', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    name: personalInfo.name,
                    email: personalInfo.email,
                    education,
                    experience,
                    projects,
                    skills
                })
            })

            const data = await response.json();
            console.log("API Response:", data);

            if (!response.ok) {
                throw new Error(data.error || 'Generation failed');
            }

            if (!data.content) {
                throw new Error('No content generated by AI');
            }

            console.log("Resume generated. Displaying inline...");
            setGeneratedResume(data.content)
            setStep(6) // Move to the new success step

        } catch (error: any) {
            console.error("Generation error:", error)
            alert("Failed to generate resume: " + (error.message || "Unknown error"))
        } finally {
            setIsGenerating(false)
        }
    }

    return (
        <div className="flex flex-col min-h-[calc(100vh-4rem)] items-center py-12 px-4 sm:px-6 lg:px-8 bg-background">
            <div className="w-full max-w-3xl space-y-8">
                <div className="text-center space-y-2">
                    <h1 className="text-4xl font-extrabold tracking-tight text-primary">Create Your Resume</h1>
                    <p className="text-muted-foreground text-lg italic">Step {step} of 5: {['Personal Info', 'Education', 'Experience', 'Projects', 'Skills & Review'][step - 1]}</p>

                    <div className="flex gap-2 justify-center mt-6">
                        {[1, 2, 3, 4, 5].map(i => (
                            <div key={i} className={`h-1.5 w-12 rounded-full transition-all duration-300 ${step >= i ? 'bg-primary' : 'bg-primary/10'}`} />
                        ))}
                    </div>
                </div>

                <Card className="border-primary/20 shadow-2xl relative overflow-hidden bg-card/50 backdrop-blur-sm">
                    <div className="absolute top-0 right-0 -z-10 w-[400px] h-[400px] bg-primary/5 rounded-full blur-3xl" />

                    <CardHeader className="border-b border-primary/10 pb-6 mb-6">
                        <CardTitle className="text-2xl font-bold flex items-center gap-2">
                            <span className="h-8 w-1 bg-primary rounded-full" />
                            {
                                step === 1 ? 'Personal Details' :
                                    step === 2 ? 'Academic Background' :
                                        step === 3 ? 'Work Experience' :
                                            step === 4 ? 'Personal Projects' :
                                                step === 5 ? 'Skills & Final Review' :
                                                    'Your Generated Resume'
                            }
                        </CardTitle>
                        <CardDescription className="pt-2">
                            {step === 5 ? "Add your key skills (comma separated) and we'll handle the rest." : step === 6 ? "Review and export your professional resume." : "Detail your information to give our AI the best context."}
                        </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">

                        {/* STEP 1: Personal Info */}
                        {step === 1 && (
                            <div className="grid gap-6 sm:grid-cols-2">
                                <div className="space-y-2">
                                    <Label className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Full Name</Label>
                                    <Input className="border-primary/10 bg-white focus-visible:ring-primary text-black" value={personalInfo.name} onChange={e => setPersonalInfo({ ...personalInfo, name: e.target.value })} placeholder="John Doe" />
                                </div>
                                <div className="space-y-2">
                                    <Label className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Email</Label>
                                    <Input className="border-primary/10 bg-white focus-visible:ring-primary text-black" type="email" value={personalInfo.email} onChange={e => setPersonalInfo({ ...personalInfo, email: e.target.value })} placeholder="john@example.com" />
                                </div>
                                <div className="space-y-2">
                                    <Label className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Phone</Label>
                                    <Input className="border-primary/10 bg-white focus-visible:ring-primary text-black" value={personalInfo.phone} onChange={e => setPersonalInfo({ ...personalInfo, phone: e.target.value })} placeholder="(555) 123-4567" />
                                </div>
                                <div className="space-y-2">
                                    <Label className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">LinkedIn URL</Label>
                                    <Input className="border-primary/10 bg-white focus-visible:ring-primary text-black" value={personalInfo.linkedin} onChange={e => setPersonalInfo({ ...personalInfo, linkedin: e.target.value })} placeholder="linkedin.com/in/johndoe" />
                                </div>
                            </div>
                        )}

                        {/* STEP 2: Education */}
                        {step === 2 && (
                            <div className="space-y-6">
                                {education.map((edu, index) => (
                                    <div key={index} className="p-6 border border-primary/10 rounded-2xl space-y-4 bg-background/40 relative group shadow-sm">
                                        <Button variant="ghost" size="icon" onClick={() => handleRemoveEducation(index)} className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity text-destructive">
                                            <Trash2 className="h-4 w-4" />
                                        </Button>
                                        <div className="grid gap-6 sm:grid-cols-2">
                                            <div className="space-y-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Degree/Certificate</Label>
                                                <Input className="border-primary/10 bg-white text-black" value={edu.degree} onChange={e => { const newEdu = [...education]; newEdu[index].degree = e.target.value; setEducation(newEdu) }} placeholder="B.S. Computer Science" />
                                            </div>
                                            <div className="space-y-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">School/University</Label>
                                                <Input className="border-primary/10 bg-white text-black" value={edu.school} onChange={e => { const newEdu = [...education]; newEdu[index].school = e.target.value; setEducation(newEdu) }} placeholder="State University" />
                                            </div>
                                            <div className="space-y-2 sm:col-span-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Year/Graduation</Label>
                                                <Input className="border-primary/10 bg-white text-black" value={edu.year} onChange={e => { const newEdu = [...education]; newEdu[index].year = e.target.value; setEducation(newEdu) }} placeholder="May 2024" />
                                            </div>
                                        </div>
                                    </div>
                                ))}
                                <Button variant="outline" className="w-full border-dashed border-primary/20 hover:bg-primary/5 hover:border-primary/40 h-12" onClick={handleAddEducation}>
                                    <Plus className="mr-2 h-4 w-4" /> Add Another Record
                                </Button>
                            </div>
                        )}

                        {/* STEP 3: Experience */}
                        {step === 3 && (
                            <div className="space-y-6">
                                {experience.map((exp, index) => (
                                    <div key={index} className="p-6 border border-primary/10 rounded-2xl space-y-4 bg-background/40 relative group shadow-sm">
                                        <Button variant="ghost" size="icon" onClick={() => handleRemoveExperience(index)} className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity text-destructive">
                                            <Trash2 className="h-4 w-4" />
                                        </Button>
                                        <div className="grid gap-6 sm:grid-cols-2">
                                            <div className="space-y-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Role/Title</Label>
                                                <Input className="border-primary/10 bg-white text-black" value={exp.role} onChange={e => { const newExp = [...experience]; newExp[index].role = e.target.value; setExperience(newExp) }} placeholder="Software Engineer" />
                                            </div>
                                            <div className="space-y-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Company</Label>
                                                <Input className="border-primary/10 bg-white text-black" value={exp.company} onChange={e => { const newExp = [...experience]; newExp[index].company = e.target.value; setExperience(newExp) }} placeholder="Tech Corp" />
                                            </div>
                                            <div className="space-y-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Duration</Label>
                                                <Input className="border-primary/10 bg-white text-black" value={exp.duration} onChange={e => { const newExp = [...experience]; newExp[index].duration = e.target.value; setExperience(newExp) }} placeholder="Jan 2022 - Present" />
                                            </div>
                                            <div className="space-y-2 sm:col-span-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Brief Description (Optional)</Label>
                                                <Textarea className="border-primary/10 bg-white min-h-[100px] text-black" value={exp.description} onChange={e => { const newExp = [...experience]; newExp[index].description = e.target.value; setExperience(newExp) }} placeholder="Worked on frontend features, improved performance by 20%..." />
                                            </div>
                                        </div>
                                    </div>
                                ))}
                                <Button variant="outline" className="w-full border-dashed border-primary/20 hover:bg-primary/5 hover:border-primary/40 h-12" onClick={handleAddExperience}>
                                    <Plus className="mr-2 h-4 w-4" /> Add Another Record
                                </Button>
                            </div>
                        )}

                        {/* STEP 4: Projects */}
                        {step === 4 && (
                            <div className="space-y-6">
                                {projects.map((project, index) => (
                                    <div key={index} className="p-6 border border-primary/10 rounded-2xl space-y-4 bg-background/40 relative group shadow-sm">
                                        <Button variant="ghost" size="icon" onClick={() => handleRemoveProject(index)} className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity text-destructive">
                                            <Trash2 className="h-4 w-4" />
                                        </Button>
                                        <div className="grid gap-6 sm:grid-cols-2">
                                            <div className="space-y-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Project Name</Label>
                                                <Input className="border-primary/10 bg-white text-black" value={project.name} onChange={e => { const newProjects = [...projects]; newProjects[index].name = e.target.value; setProjects(newProjects) }} placeholder="E-commerce App" />
                                            </div>
                                            <div className="space-y-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Your Role</Label>
                                                <Input className="border-primary/10 bg-white text-black" value={project.role} onChange={e => { const newProjects = [...projects]; newProjects[index].role = e.target.value; setProjects(newProjects) }} placeholder="Lead Developer" />
                                            </div>
                                            <div className="space-y-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Duration</Label>
                                                <Input className="border-primary/10 bg-white text-black" value={project.duration} onChange={e => { const newProjects = [...projects]; newProjects[index].duration = e.target.value; setProjects(newProjects) }} placeholder="3 Months" />
                                            </div>
                                            <div className="space-y-2 sm:col-span-2">
                                                <Label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Description (Optional)</Label>
                                                <Textarea className="border-primary/10 bg-white min-h-[100px] text-black" value={project.description} onChange={e => { const newProjects = [...projects]; newProjects[index].description = e.target.value; setProjects(newProjects) }} placeholder="Built a full-stack e-commerce application using Next.js and Stripe." />
                                            </div>
                                        </div>
                                    </div>
                                ))}
                                <Button variant="outline" className="w-full border-dashed border-primary/20 hover:bg-primary/5 hover:border-primary/40 h-12" onClick={handleAddProject}>
                                    <Plus className="mr-2 h-4 w-4" /> Add Another Project
                                </Button>
                            </div>
                        )}

                        {/* STEP 5: Skills */}
                        {step === 5 && (
                            <div className="space-y-4">
                                <div className="space-y-2">
                                    <Label className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Skills (Comma Separated)</Label>
                                    <Textarea
                                        value={skills}
                                        onChange={e => setSkills(e.target.value)}
                                        placeholder="JavaScript, React, Node.js, Project Management..."
                                        className="min-h-[150px] text-lg p-4 border-primary/20 bg-white focus-visible:ring-primary text-black"
                                    />
                                </div>
                                <div className="bg-primary/5 p-6 rounded-2xl flex items-center justify-between border border-primary/10">
                                    <p className="text-sm text-primary/80 mr-4 font-medium">
                                        Our AI will transform these details into a high-impact, professional resume structured for maximum visibility.
                                    </p>
                                    <div className="h-12 w-12 bg-primary/20 flex items-center justify-center rounded-full shrink-0 text-2xl">
                                        🚀
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* STEP 6: Generated Resume Display */}
                        {step === 6 && generatedResume && (
                            <div className="space-y-6">
                                <div className="bg-primary/5 border border-primary/20 p-6 rounded-2xl flex flex-col sm:flex-row items-center justify-between gap-4">
                                    <div className="flex items-center gap-3">
                                        <CheckCircle className="h-8 w-8 text-green-500" />
                                        <div>
                                            <h3 className="font-bold text-lg">Resume Generated Successfully!</h3>
                                            <p className="text-sm text-muted-foreground">Your resume is ready. You can now export it.</p>
                                        </div>
                                    </div>
                                    <ExportPdfButton />
                                </div>
                                <div className="max-w-4xl w-full mx-auto py-8 px-8 shadow-inner border border-stone-200 bg-white rounded-xl printable-resume overflow-auto max-h-[60vh]">
                                    <div className="prose prose-stone prose-sm sm:prose-base max-w-none text-black">
                                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                            {generatedResume}
                                        </ReactMarkdown>
                                    </div>
                                </div>
                            </div>
                        )}

                    </CardContent>
                    <CardFooter className="flex justify-between bg-primary/5 p-6 border-t border-primary/10">
                        {step < 6 && (
                            <Button variant="outline" onClick={() => setStep(s => Math.max(1, s - 1))} disabled={step === 1 || isGenerating} className="border-primary/20 hover:bg-primary/5">
                                Back
                            </Button>
                        )}

                        {step === 6 && (
                            <Button variant="outline" onClick={() => router.push('/dashboard')} className="border-primary/20 hover:bg-primary/5">
                                Return to Dashboard
                            </Button>
                        )}

                        {step < 5 ? (
                            <Button onClick={() => setStep(s => Math.min(5, s + 1))} className="bg-primary hover:bg-primary/90 px-8">
                                Continue
                            </Button>
                        ) : step === 5 ? (
                            <Button onClick={handleGenerate} disabled={isGenerating} size="lg" className="px-10 bg-primary hover:bg-primary/90 shadow-xl shadow-primary/20">
                                {isGenerating ? (
                                    <>
                                        <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                                        Crafting your profile...
                                    </>
                                ) : (
                                    'Generate with AI ✨'
                                )}
                            </Button>
                        ) : null}
                    </CardFooter>
                </Card>
            </div>
        </div>
    )
}
